"""initial migration

Revision ID: 11a39d9e0bd7
Revises: 
Create Date: 2025-06-24 20:17:54.683689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11a39d9e0bd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climate', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'city', ['ciudad_id'], ['id'])
        batch_op.drop_column('city_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
