"""add attr to climate model

Revision ID: 4d9ce816e3f7
Revises: d0dc99a75514
Create Date: 2025-06-25 21:26:31.246879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d9ce816e3f7'
down_revision = 'd0dc99a75514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('windspeed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('winddirection', sa.Float(), nullable=True))
        batch_op.alter_column('temperature',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climate', schema=None) as batch_op:
        batch_op.alter_column('temperature',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.drop_column('winddirection')
        batch_op.drop_column('windspeed')

    # ### end Alembic commands ###
