"""initial migration

Revision ID: d0dc99a75514
Revises: 
Create Date: 2025-06-25 21:07:31.599325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0dc99a75514'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climate', schema=None) as batch_op:
        batch_op.drop_column('windspeed')
        batch_op.drop_column('winddirection')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winddirection', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('windspeed', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
