"""add climate table

Revision ID: ec420f441e9d
Revises: b6095fa6de09
Create Date: 2025-06-10 20:39:53.939315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec420f441e9d'
down_revision = 'b6095fa6de09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('ciudad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ciudad_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('climate')
    # ### end Alembic commands ###
